AWSTemplateFormatVersion: "2010-09-09"
Description: "Plantilla LoadBalancer - Yasir" 

Parameters: 
  InstanceTypeParameter: 
    Description: Elige un tipo de instancia. 
    Type: String
    Default: t2.large
    AllowedValues:
      - t2.micro
      - m1.small
      - t2.large
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/canonical/ubuntu/server/jammy/stable/current/amd64/hvm/ebs-gp2/ami-id'

Resources: 
  LoadBalancerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref LatestAmiId
      SecurityGroupIds:
        - !ImportValue securitygroup-LoadBalancer
      UserData:
        Fn::Base64: !Sub
          - |
            #!/bin/bash
            apt update -y
            apt install -y nginx
            rm -f /etc/nginx/sites-enabled/default
            cat > /etc/nginx/conf.d/loadbalancer.conf <<EOF
            upstream frontend {
                server ${FE1}:80;
                server ${FE2}:80;
            }

            server {
                listen 80;
                server_name _;
                
                location / {
                    proxy_pass http://frontend;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                }
            }
            EOF
            nginx -t && systemctl restart nginx
            systemctl enable nginx
          - { FE1: !ImportValue FE1IP, FE2: !ImportValue FE2IP }

Outputs:
  LoadBalancerPublicIP:
    Description: "IP publica de la instancia Load Balancer"
    Value: !GetAtt LoadBalancerInstance.PublicIp
    Export:
      Name: LoadBalancerPublicIP
